spring:
  datasource: 
    url: jdbc:mysql://localhost:3306/sample?createDatabaseIfNotExist=true
    username: yuva
    password: yuva
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  
