
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: yuva
    password: yuva
    testWhileIdel: true
    validationQuery: SELECT 1
 jpa: 
   show-sql: true
   hibernate: 
     namimg-strategy: org.hibernate.cfg.ImprovedNamingStrategy
     ddl-auto: update  
   database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
